### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by SimonKitSangChu** [xqding/PEVAE_Paper#1]
Fail to launch script/analyze_model.py. Cannot find module model in repository.

```
python script/analyze_model.py 
Traceback (most recent call last):
  File "script/analyze_model.py", line 9, in <module>
    from model import *
ModuleNotFoundError: No module named 'model'
```

**Comment by xqding** [comment]
Thanks for raising the issue. Replace the line `from model import *` with `from VAE_model improt *` in the file `script/analyze_model.py` should be able to fix the problem.

**Comment by SimonKitSangChu** [comment]
After updating the import line, there is another issue.
```
python ./script/analyze_model.py 
Traceback (most recent call last):
  File "./script/analyze_model.py", line 34, in <module>
    train_data = MSA_Dataset(seq_msa_binary, seq_weight)
TypeError: __init__() missing 1 required positional argument: 'seq_keys'
```

**Comment by xqding** [comment]
Could you try it again? It should be fixed.

**Comment by SimonKitSangChu** [comment]
git pull-ed to commit b90f8e205101a1d204a47eb6202e12da71ebc00f. Error persists after merging.
